services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /mnt/storage/Media/:/mnt/storage/Media/
      - /mnt/storage/Downloads/:/mnt/storage/Downloads/
    ports:
      - 8989:8989
    depends_on:
      - prowlarr
      - transmission
    networks:
      - mediaserver
    restart: unless-stopped

networks:
    mediaserver:
          external: true

