services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - ./config:/config
    networks:
      - mediaserver


networks:
  mediaserver:
    external: true
