services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ./config/:/config
      - /mnt/storage/_Dump/Audiobooks:/audiobooks

networks:
  mediaserver:
    external: true
