services:
  cross-seed:
    image: crossseed/cross-seed
    container_name: cross-seed
    volumes:
      - ./config:/config
      - ../transmission/config/transmission-home/torrents/:/torrents:ro
      # note that this volume can and should be mounted read-only
    depends_on:
      - jackett
      - prowlarr
      - transmission
    ports:
      - 2468:2468
    networks:
      - mediaserver
    command: daemon

networks:
  mediaserver:
    external: true
