services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    volumes:
      - /mnt/storage/Downloads/:/mnt/storage/Downloads/
      - ./config/:/config
      - ./protonvpn:/etc/openvpn/custom/
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_DOWNLOAD_DIR=/mnt/storage/Downloads/
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_SEED_QUEUE_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_UTP_ENABLED=false
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=10.0.0.0/16

    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - proton.env
    networks:
      - mediaserver
networks:
  mediaserver:
    external: true
